---
- name: PGBouncer | Install from apt repo
  apt:
    name: pgbouncer
    state: present

- name: PGBouncer | Install postgresql-client
  apt:
    name: postgresql-client
    state: installed
  when: pgbouncer_install_pg_client == True

- name: PGBouncer | Configure pgbouncer
  template:
    src: ../templates/pgbouncer.ini.j2
    dest: "{{ pgbouncer_conf_file }}"
  notify:
    - pgbouncer_reload

- name: PGBouncer | Configure auth_users list
  template:
    src: ../templates/userlist.txt.j2
    dest: "{{ pgbouncer_auth_file }}"
  notify:
    - pgbouncer_reload

- name: PGBouncer | Configure pgbouncer to start at boot
  replace:
    regexp: '^START=0'
    replace: 'START=1'
    dest: /etc/default/pgbouncer
  when: pgbouncer_start_on_boot == True
